services:
  - type: web
    name: bank-django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn BankManagement.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: BankManagement.settings
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: your-render-app-name.onrender.com
      - key: DATABASE_URL
        value: mysql://your_db_user:your_db_password@your_db_host:3306/your_db_name
